// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION @MAJOR_VERSION@
#define MINOR_VERSION @MINOR_VERSION@
#define REVISION @REVISION@

#define BUILD_NUMBER @GIT_BUILD_NUMBER@
#define COMMIT_HASH "@GIT_COMMIT_HASH@"

#endif // VERSION_AUTOGEN_H
