// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 1
#define MINOR_VERSION 2
#define REVISION 0

#define BUILD_NUMBER 614
#define COMMIT_HASH "f8b4f812ef8dacf47203d9f4f296c6581ff835c0"

#endif // VERSION_AUTOGEN_H
