// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 1
#define MINOR_VERSION 1
#define REVISION 1

#define BUILD_NUMBER 487
#define COMMIT_HASH "cded33fed2b5a5af6eda94864149ca45089f8960"

#endif // VERSION_AUTOGEN_H
