// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 1
#define MINOR_VERSION 1
#define REVISION 0

#define BUILD_NUMBER 442
#define COMMIT_HASH "609614400d6b19385261cf0f9d1f90ade4145d4c"

#endif // VERSION_AUTOGEN_H
