// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 1
#define MINOR_VERSION 0
#define REVISION 0

#define BUILD_NUMBER 384
#define COMMIT_HASH "c9126860fcfe57d62727f4204c943df3aff42ddf"

#endif // VERSION_AUTOGEN_H
